name: thehoister
favicon: null
layout_spectrum: 0.9323782024439424
typography_spectrum: 0.4719101330265403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4452621580567211
  lightness: 0.21160245197825134
  saturation: 0.5745132989250124
  rhythmicContrast: 0.05587119818665087
purpose: []
